#CASO NÃO QUEIRA HABILITAR O DINHEIRO DEIXE COMO 0.0
#CASO NÃO QUEIRA HABILITAR O COMANDO DEIXE COMO ''
#PARA PEGAR O NOME DOS EVENTOS USE /EVENTOS LIST E COLOQUE EM LETRAS MINÚSCULAS


# Use %player% para substituir o nome do jogador